artifacts_root : artifacts

data_ingestion  : 
  root_dir      : artifacts/datas
  image_path    : artifacts/datas/image
  mask_path     : artifacts/datas/mask
  csv_file_path : artifacts/datas/images_masks.csv
  train_path    : artifacts/datas/train.csv
  test_path     : artifacts/datas/test.csv
  val_path      : artifacts/datas/val.csv


prepare_base_model:
  root_dir                : artifacts/prepare_base_model
  base_model_path         : artifacts/prepare_base_model/base_model.h5
  updated_base_model_path : artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir                  : artifacts/prepare_callbacks
  tensorboard_root_log_dir  : artifacts/prepare_callbacks/tensorbord_log_dir
  checkpoint_model_filepath : artifacts/prepare_callbacks/checkpoint_dir/model.h5
